version: '3.1'

services:
  app:
    image: 'eshop-docker:latest'
    build: ./
    container_name: app
    depends_on:
      - my-postgres
    ports:
      - "8080:8080"
  my-postgres:
    image: 'postgres:latest'
    container_name: my-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=shop
    ports:
      - "5432:5432"