version: '2'

services:
  app:
    image: 'eshop-docker:latest'
    build:
      context: src/main
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5432/shop
      - SPRING_DATASOURCE_USERNAME= root
      - SPRING_DATASOURCE_PASSWORD= alp2226177
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8085:8085"
  db:
    image: 'postgres:latest'
    volumes:
      - ./postgresql/:/var/lib/postgresql/data/
    container_name: db
    environment:
      - POSTGRES_USER= root
      - POSTGRES_PASSWORD= alp2226177
    ports:
      - "5432:5432"