spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://my-postgres:5432/shop
    username: postgres
    password: 1
  flyway:
    baseline-on-migrate: true
  main:
    allow-circular-references: true
  datasource.driver-class-name: org.postgresql.Driver
  jpa.open-in-view: false
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
server:
  port: 8080
