spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: root
    password: alp2226177
  flyway:
    baseline-on-migrate: true
  main:
    allow-circular-references: true
  datasource.driver-class-name: org.postgresql.Driver
  jpa.open-in-view: false
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

